use serde_json::Value;
use std::collections::BTreeSet;
use std::fs;
use std::path::PathBuf;

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn text(path: &str) -> String {
    fs::read_to_string(root().join(path)).unwrap_or_else(|error| panic!("{path}: {error}"))
}

fn json(path: &str) -> Value {
    serde_json::from_str(&text(path)).unwrap_or_else(|error| panic!("{path}: {error}"))
}

#[test]
fn manifest_registers_one_menu_item_with_playground_and_demo_tabs() {
    let manifest = json("ui/manifest.json");
    assert_eq!(manifest["schema"], "pom-plugin-ui/v1");
    assert_eq!(manifest["plugin_code"], "jev");
    assert_eq!(manifest["icon_image"], "ui/icon.png");
    let menu = manifest["menu"].as_array().expect("menu");
    assert_eq!(menu.len(), 1);
    assert_eq!(menu[0]["label"]["en"], "POM-JEV");
    assert_eq!(menu[0]["to"], "/jev");
    assert!(menu[0].get("children").is_none());
    let routes = manifest["routes"].as_array().unwrap();
    assert_eq!(routes.len(), 1);
    assert_eq!(routes[0]["path"], "/jev");
    assert_eq!(routes[0]["screen"], "jev");
    assert_eq!(routes[0]["full_bleed"], true);
    assert_eq!(manifest["screens"]["jev"]["export"], "jev");
    assert_eq!(manifest["screens"]["jev"]["module"], "ui/screens.js");
    assert!(text("ui/src/screens/index.tsx").contains("JevApp as jev"));
    let app = text("ui/src/screens/JevApp.tsx");
    assert!(app.contains("<Playground />") && app.contains("<Demo />"));
}

#[test]
fn menu_icons_exist_in_the_pom_host() {
    // Icons the POM sidebar knows (`apps/frontend/src/components/nav.ts`).
    let known = [
        "blocks",
        "messages-square",
        "list-tree",
        "book-open",
        "folder-tree",
    ];
    let manifest = json("ui/manifest.json");
    for icon in [manifest["menu"][0]["icon"].clone()] {
        assert!(known.contains(&icon.as_str().unwrap()), "{icon}");
    }
}

#[test]
fn assets_and_documentation_exist() {
    let manifest = json("ui/manifest.json");
    for asset in manifest["assets"].as_array().unwrap() {
        let path = asset.as_str().unwrap();
        if path.starts_with("ui/") && path.ends_with(".js") || path.ends_with(".css") {
            continue; // generated by scripts/build-ui.sh
        }
        if path.starts_with("i18n/") {
            assert!(root().join(path).is_file(), "missing {path}");
            continue;
        }
        assert!(root().join(path).is_file(), "missing {path}");
    }
    for doc in manifest["documentation"].as_array().unwrap() {
        assert!(root().join(doc.as_str().unwrap()).is_file());
    }
    for shot in manifest["screenshots"].as_array().unwrap() {
        let path = shot.as_str().unwrap();
        let bytes = fs::read(root().join(path)).unwrap_or_else(|error| panic!("{path}: {error}"));
        assert!(bytes.starts_with(b"\x89PNG\r\n\x1a\n"), "{path}");
    }
    for locale in ["en", "pt-BR"] {
        assert!(!manifest["description"][locale]
            .as_str()
            .unwrap()
            .trim()
            .is_empty());
    }
}

#[test]
fn catalogs_match_and_cover_every_static_key() {
    let en = json("i18n/en.json");
    let pt = json("i18n/pt-BR.json");
    let en_keys: BTreeSet<_> = en.as_object().unwrap().keys().cloned().collect();
    let pt_keys: BTreeSet<_> = pt.as_object().unwrap().keys().cloned().collect();
    assert_eq!(en_keys, pt_keys);
    for path in ["ui/src/screens/Playground.tsx", "ui/src/screens/Demo.tsx"] {
        let source = text(path);
        for (index, _) in source.match_indices("t(\"") {
            let before = source[..index].chars().next_back();
            if before.is_some_and(|c| c.is_alphanumeric() || c == '_') {
                continue;
            }
            let key = source[index + 3..].split_once('"').unwrap().0;
            if key == "2d" {
                continue;
            }
            assert!(en_keys.contains(key), "{path}: missing key {key}");
        }
    }
    for cause in ["wall", "body", "trapped"] {
        assert!(en_keys.contains(&format!("demo.cause.{cause}")));
    }
}

#[test]
fn release_contract_and_workflow_publish_to_github_only() {
    let release = json("release/manifest.json");
    assert_eq!(release["schema"], 1);
    assert_eq!(release["plugin_code"], "jev");
    assert_eq!(release["feature_set"], serde_json::json!(["jev.core"]));
    let workflow = text(".github/workflows/publish-release.yml");
    assert!(workflow.contains("dist-release/pom-plugin-jev-${{ matrix.platform }}"));
    assert!(workflow.contains("softprops/action-gh-release"));
    assert!(!workflow.contains("license-server") && !workflow.contains("POM_RELEASE_TOKEN"));
    let build = text("scripts/build.sh");
    assert!(build.contains("libpom_plugin_jev"));
    let cargo = text("Cargo.toml");
    assert!(cargo.contains("name = \"pom-plugin-jev\""));
    assert!(cargo.contains("crate-type = [\"cdylib\"]"));
}

#[test]
fn the_browser_never_holds_the_gateway_key() {
    let client = text("ui/src/jev.ts");
    assert!(client.contains("/proxy`") || client.contains("/proxy"));
    assert!(!client.contains("api_key"));
    let native = text("src/lib.rs");
    assert!(native.contains("\"/decide\""));
    assert!(native.contains("DECISION_PATH: &str = \"/systemone\""));
    assert!(native.contains("Authorization"));
}
